[build]
  base = ""
  publish = "packages/playground/dist"
  command = "npm run build-serial"
  # Ignore dependabot PRs for deploy previews
  ignore = "./netlify-ignore.sh"

[build.environment]
  VITE_SHOW_NETLIFY_BADGE = "true"
  NODE_VERSION = "18"
