import type { FormContextType, RJSFSchema, StrictRJSFSchema, ValidatorType } from '@rjsf/utils';

import ATAPrecompiledValidator from './precompiledValidator.ts';
import type { PrecompiledValidatorOptionsType, ValidatorFunctions } from './types.ts';

/** Creates and returns a `ValidatorType` interface that is implemented with a precompiled validator. If a `localizer`
 * is provided, it is used to translate the messages generated by the underlying ata validation.
 *
 * NOTE: The `validateFns` parameter is an object obtained by importing from a precompiled validation file created via
 * the `compileSchemaValidators()` function.
 *
 * @param validateFns - The map of the validation functions that are created by the `compileSchemaValidators()` function
 * @param rootSchema - The root schema that was used with the `compileSchemaValidators()` function
 * @param [options] - The `PrecompiledValidatorOptionsType` the validator is constructed with: a `localizer`, a
 *        `suppressDuplicateFiltering` and the `customMergeAllOf` the schemas were compiled with, which must match the
 *        one passed to `compileSchemaValidatorsCode()` so the sub-schemas it builds hash to entries the precompiled
 *        map holds
 * @returns - The precompiled validator implementation resulting from the set of parameters provided
 */
export default function createPrecompiledValidator<
  S extends StrictRJSFSchema = RJSFSchema,
  F extends FormContextType = FormContextType,
>(validateFns: ValidatorFunctions, rootSchema: S, options?: PrecompiledValidatorOptionsType<S>): ValidatorType<S, F> {
  return new ATAPrecompiledValidator<S, F>(validateFns, rootSchema, options);
}
