name: 🐛 Bug
description: File a bug/issue
title: '<title>'
labels: [bug, needs triage]
assignees:
  - rjsf-team/reviewers
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: I have searched the existing issues
          required: true
        - label: I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
          required: true
        - label: I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
          required: true
        - label: Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.
          required: false
  - type: dropdown
    id: theme
    attributes:
      label: What theme are you using?
      options:
        - core
        - antd
        - bootstrap-4
        - chakra-ui
        - fluent-ui
        - material-ui
        - mui
        - semantic-ui
        - utils
        - validator-ajv6
        - validator-ajv8
        - other
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.
      value: 5.x
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: Ubuntu 20.04
          - **Node**: 13.14.0
          - **npm**: 7.6.3
      value: |
        - OS:
        - Node:
        - npm:
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
