name: ❔ Question
description: Ask a Question
title: '<title>'
labels: [question, needs triage]
assignees:
  - rjsf-team/reviewers
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
          required: true
  - type: dropdown
    id: theme
    attributes:
      label: What theme are you using?
      options:
        - antd
        - chakra-ui
        - core
        - daisyui
        - fluentui-rc
        - mui
        - react-bootstrap
        - semantic-ui
        - shadcn
        - utils
        - validator-ajv8
        - other
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is your question?
    validations:
      required: false
