name: issue-triage-removal-automation

on:
  issues:
    types: [assigned]

jobs:
  automate-issues-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: andymckay/labeler@1.0.4
        with:
          remove-labels: 'needs triage'
          ignore-if-assigned: false
